Improve building of python kernel API.
Unfortunately, it doesn't quite work yet. Problem with C++ typedef translation:
> python bin/yask-kernel-api-test.py
 TypeError: in method 'yk_settings_set_domain_size', argument 3 of type 'yask::idx_t'

Also, build compiler API manually instead of via distutils.